# Generated by Django 5.1.6 on 2025-05-06 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_endpoint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailchangerequest",
            name="expires_at",
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
        migrations.AddField(
            model_name="forgotpasswordrequest",
            name="expires_at",
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
        migrations.AddField(
            model_name="passwordchangerequest",
            name="expires_at",
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
