# Generated by Django 5.1.6 on 2025-05-07 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_endpoint", "0002_emailchangerequest_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forgotpasswordrequest",
            name="id",
        ),
        migrations.AddField(
            model_name="forgotpasswordrequest",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("a6f54a18-8fcd-44f5-86d1-e81d6da44262"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
