# Generated by Django 5.1.6 on 2025-05-09 00:59

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_endpoint", "0003_remove_forgotpasswordrequest_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgotpasswordrequest",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f2c2aed5-04da-4b40-b7fc-25c4c5b62027"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="ForgotPasswordChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_fulfilled_at", models.DateTimeField(null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 9, 17, 59, 31, 465948)
                    ),
                ),
                ("request_cancelled", models.BooleanField(default=False)),
                (
                    "original_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_endpoint.forgotpasswordrequest",
                    ),
                ),
            ],
        ),
    ]
