# Generated by Django 5.1.6 on 2025-05-09 03:41

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_endpoint", "0004_alter_forgotpasswordrequest_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgotpasswordchangerequest",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 10, 3, 41, 41, 340120)
            ),
        ),
        migrations.AlterField(
            model_name="forgotpasswordrequest",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("563f0be1-e3c1-42d5-a329-3ef8b1b5c543"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
