# Generated by Django 5.1.6 on 2025-05-09 03:43

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_endpoint", "0005_alter_forgotpasswordchangerequest_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgotpasswordchangerequest",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 10, 3, 43, 51, 825729, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="forgotpasswordrequest",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("2dbde932-82bb-417a-9c74-4d9e1dc07d27"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
