# Generated by Django 5.1.6 on 2025-05-09 04:00

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_endpoint", "0008_alter_forgotpasswordchangerequest_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgotpasswordchangerequest",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 10, 4, 0, 32, 974071, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="forgotpasswordrequest",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("fae2e7c4-512f-4750-80fd-4ca07b6150e7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
