# Generated by Django 5.1.6 on 2025-05-09 04:01

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_endpoint", "0009_alter_forgotpasswordchangerequest_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgotpasswordchangerequest",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 10, 4, 1, 56, 816270, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="forgotpasswordrequest",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("83015346-c8b3-45d8-af26-ce8db4625a5a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
